const all_Titles = [
    "Gameification",
    "Emerging Technology",
    "Whistle Blowing",
    "Ai Art",
];

const all_Overviews = [
    "TEMP MOVE TEXT HERE",
    "TEMP MOVE TEXT HERE",
    "Whistle blowing is when an employee working at an organisation exposes their bad practises, particually when that information is in the public intrest, such as a company hurting the health of their customers or defrauding consumers.",
    "Recent developments in ai art have taken the internet by storm. We have seen online art boards get bombarded by low quality ai posts and fascinating works, the likes of which no one has seen before. Artists have been uploading hundreds of anti ai protest images which makes us wonder whether they have a point or are just resentful of other people being able to create their own impressive works.",
]

const all_Header1 = [
    "TEMP MOVE TEXT HERE",
    "TEMP MOVE TEXT HERE",
    "What counts as whistleblowing?",
    "How Ai Art is Made",
]

const all_Para1 = [
    "TEMP MOVE TEXT HERE",
    "TEMP MOVE TEXT HERE",

    "The term 'whistleblowing' is used when a worker reports wrongdoing. According to the government: 'As a whistleblower you're protected by law - you should not be treated unfairly or lose your job because you 'blow the whistle'."
    + " Valid complaints that constitute as whisteblowing are: "
    + "<ul><li>" +
    "Criminal offences such as fraud" +
    "</li><li>" +
    "Damage to the environment or people's health" +
    "</li><li>" +
    "Coverups" + "</li></ul>"
    + "Some grievances such as bullying or discrimination are not covered under whistleblowing law and you will not be protected. <strong>Whistleblowing law is only applicable when your case is in the public interest.</strong>",
    "Ai art is made by training generative adversarial networks on millions of images of 'real' art. It then produces its own art and attempts to fool the 'discriminator' into thinking that it has produced a real art. It continually gets better at creating human-like art and can even make 'original' pieces of work.",
,
]

const all_Header2 = [
    "",
    "",
    "Case Studies",
    "Why has it Created Controversy?",
]

const all_Para2 = [
    "",
    "",
    "<ul><li>" +
    "Frances Haugen - Former Facebook employee who blew the whistle, believing that Facebook was misleading the public on 'how it handles issues such as climate change, misinformation and hate speech'. " +
    "</li><li>" +
    "Tyler Schultz - Former Theranos employee who exposed their fraudulent blood testing" +
    "</li><li>" +
    "Cher Scarlett - A software engineer who worked at organisation such as apple and blizzard who advocated for fair labour practices.'" + "</li></ul>",
    "When the creators of an ai want to train it, they need to gather a diverse range of training data. This often leads to using millions of miscellaneous images off the internet, usually without permission of the creators of this work. These leads may artists to feel as if their work has been stolen and simply remixed by the ai. Furthermore, ai art has been entered into art competitions, which is unfair to the real artists in the world who pour hours of their own time into creating completely original pieces of work only to be beaten by someone who has spent 10 minutes submitting work generated by an ai. Creators are also concerned about having their source of income taken away from ai. Artists rely upon commissions for art projects from automotive companies, movie studios, game studios and other businesses.These businesses could simply use an ai to do the work and in much less time. With ai art where it is now, people say that ai art will be used as a tool to aid artists, much like how autopilot systems aid pilots. However, it remains to be seen whether artists could stick around like pilots or get replaced.",
]

function update_Content(instance) {
    let title = all_Titles[instance];
    let overview = all_Overviews[instance];
    let left_Header = all_Header1[instance];
    let left_Para = all_Para1[instance];
    let right_Header = all_Header2[instance];
    let right_Para = all_Para2[instance];

    document.getElementById("title").innerHTML = title;
    document.getElementById("overview").innerHTML = overview;
    document.getElementById("left_Header").innerHTML = left_Header;
    document.getElementById("left_Para").innerHTML = left_Para;
    document.getElementById("right_Header").innerHTML = right_Header;
    document.getElementById("right_Para").innerHTML = right_Para;
}

// Lets the section that has been linked get passed as an argument
var parameters = location.search.substring(1).split("&");
parameters = parameters[0].split("=");


var temp_Index = 0;
if (parameters[0] == "page") {
    temp_Index = parameters[1];
}

update_Content(temp_Index);

